import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { useEffect, useState } from "react";
import Layout from "../../components/Layout";
import Footer from "../../components/Footer";

// import { connect } from "../../utils/connection";

function Comrade() {
  const [comrade, setComrade] = useState({
    status: "",
    from: "",
    to: "",
  });
  const [isLoading, setIsLoading] = useState(true);
  const [isValidID, setIsValidID] = useState(true);
  useEffect(() => {
    console.log("Comrade useEffect");
    // const { id } = router.query;
    // console.log(router);
    const id = window.location.pathname.split("/")[2];
    fetch("/api/comrades/" + id, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    })
      .then((res) => res.json())
      .then((result) => {
        console.log(result);
        if (result) {
          setComrade(result);
          setIsValidID(true);
        } else {
          // return router.push("/"+id);
          setIsValidID(false);
        }
        setIsLoading(false);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {isLoading ? (
          <div className="flex items-center justify-center h-screen">
            please wait...
          </div>
        ) : (
          <section className="">
            {isValidID ? (
              <div className="flex flex-col">
                <h2 className="">{comrade.name}</h2>
                <p className="text-sm">{comrade.department}</p>
                <p className="text-sm">{comrade.gpa}</p>
              </div>
            ) : (
              <h2 className="">Comrade not found</h2>
            )}
            <button>Enroll here</button>
          </section>
        )}
      </Layout>

      <Footer />
    </div>
  );
}

// TODO: Create basic styling
// TODO: Fetch graduates from API

export default Comrade;
