import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Layout from "../components/Layout";
import Footer from "../components/Footer";

import { connect } from "../utils/connection";

export default function Home({ comrades}) {
  console.log(comrades)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section className="">
          <h1 className="text-3xl">We love Vawulence!</h1>
          <p>Become a certified something of Vawulence Today</p>

          <button>Click me</button>
        </section>

        <section className="">
          <h2 className="">Current Holders of Vawulence</h2>

          <button>Click me</button>
        </section>
      </Layout>

      <Footer/>
    </div>
  );
}

export const getStaticProps = async () => {
  // const res = await axios.get('/api/ip');
  const { Comrade } = await connect();
  // console.log(s)
  const comrades = await Comrade.find() // get all comrades
        .then((comrades) => {
          console.log(comrades, "qwert")
          res.json(comrades);
        }) // return comrades

  return {
    props: { comrades },
    revalidate: 20,
  };
};


// TODO: Create basic styling
// TODO: Fetch graduates from API