import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Layout from "../components/Layout";
import Footer from "../components/Footer";

import { connect } from "../utils/connection";

function Home({comrades}) {
  console.log(comrades)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section className="">
          <h1 className="text-3xl">We love Vawulence!</h1>
          <p>Become a certified something of Vawulence Today</p>

          <button>Enroll here</button>
        </section>

        <section className="">
          <h2 className="">Current Holders of Vawulence</h2>
          <div className="flex flex-wrap">
            {comrades.map((comrade) => (
              <div className="w-1/2 p-4" key={comrade._id}>
                <div className="flex flex-col">
                  <div className="flex flex-row">
                    {/* <Image
                      src={comrade.image}
                      width={100}
                      height={100}
                      alt={comrade.name}
                    /> */}
                    <div className="flex flex-col ml-4">
                      <h3 className="text-xl">{comrade.name}</h3>
                      <p className="text-sm">{comrade.department}</p>
                      <p className="text-sm">{comrade.gpa}</p>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
                      
          <button>Enroll here</button>
        </section>
      </Layout>

      <Footer/>
    </div>
  );
}

export async function getStaticProps() {
  // const res = await axios.get('/api/ip');
  const { Comrade } = await connect();
  // console.log(s)
  const comrades = await Comrade.find() // get all comrades
        .then((res) => {
          console.log(res, "qwert")
          // res.json(comrades);
          return res;
        }) // return comrades
        console.log(comrades, "comrades")
        // .catch((err) => console.log(err)); // catch errors
  return {

    props: {
      comrades: JSON.parse(JSON.stringify(comrades))
    },
    revalidate: 20,
  };
};


// TODO: Create basic styling
// TODO: Fetch graduates from API

export default Home;